# automatically generated by the FlatBuffers compiler, do not modify

# namespace: circle

class FullyConnectedOptionsWeightsFormat(object):
    DEFAULT = 0
    SHUFFLED4x16INT8 = 1
    SHUFFLED16x1FLOAT32 = 127

